export const MOCK_BOLSAS = [ 
 {
    instituicao: 'Universidade Leste',
    estado: 'CE',
    cidade: 'Fortaleza',
    bairro: 'Meireles',
    curso: 'Engenharia Civil',
    turno: 'Tarde',
    modalidade: 'Presencial',
    alt: 'Logo da Universidade Leste',
    logo: 'https://cdn-icons-png.flaticon.com/512/197/197484.png',
    serie: '2ª',
    precoComDesconto: '1400,00'
  },
  {
    instituicao: 'Faculdade Centro Sul',
    estado: 'PR',
    cidade: 'Curitiba',
    bairro: 'Batel',
    curso: 'Medicina',
    turno: 'Integral',
    modalidade: 'Presencial',
    alt: 'Logo da Faculdade Centro Sul',
    logo: 'https://cdn-icons-png.flaticon.com/512/167/167707.png',
    serie: '5ª',
    precoComDesconto: '3500,00'
  },
  {
    instituicao: 'Instituto Tecnológico Norte',
    estado: 'AM',
    cidade: 'Manaus',
    bairro: 'Adrianópolis',
    curso: 'Tecnologia da Informação',
    turno: 'Noite',
    modalidade: 'EAD',
    alt: 'Logo do Instituto Tecnológico Norte',
    logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    serie: '3ª',
    precoComDesconto: '1200,00'
  },
  {
    instituicao: 'Centro de Ensino Oeste',
    estado: 'GO',
    cidade: 'Goiânia',
    bairro: 'Setor Bueno',
    curso: 'Direito',
    turno: 'Manhã',
    modalidade: 'Presencial',
    alt: 'Logo do Centro de Ensino Oeste',
    logo: 'https://cdn-icons-png.flaticon.com/512/196/196566.png',
    serie: '4ª',
    precoComDesconto: '1600,00'
  },
  {
    instituicao: 'Faculdade Litoral',
    estado: 'PE',
    cidade: 'Recife',
    bairro: 'Boa Viagem',
    curso: 'Arquitetura',
    turno: 'Tarde',
    modalidade: 'Presencial',
    alt: 'Logo da Faculdade Litoral',
    logo: 'https://cdn-icons-png.flaticon.com/512/2991/2991148.png',
    serie: '3ª',
    precoComDesconto: '1500,00'
  },
  {
    instituicao: 'Universidade Central',
    estado: 'DF',
    cidade: 'Brasília',
    bairro: 'Asa Norte',
    curso: 'Administração Pública',
    turno: 'Manhã',
    modalidade: 'EAD',
    alt: 'Logo da Universidade Central',
    logo: 'https://cdn-icons-png.flaticon.com/512/2942/2942549.png',
    serie: '2ª',
    precoComDesconto: '1100,00'
  },
  {
    instituicao: 'Faculdade Montanha',
    estado: 'SC',
    cidade: 'Florianópolis',
    bairro: 'Trindade',
    curso: 'Engenharia Elétrica',
    turno: 'Noite',
    modalidade: 'Presencial',
    alt: 'Logo da Faculdade Montanha',
    logo: 'https://cdn-icons-png.flaticon.com/512/3284/3284391.png',
    serie: '4ª',
    precoComDesconto: '1700,00'
  },
  {
  instituicao: 'Faculdade Estácio',
  estado: 'RJ',
  cidade: 'Rio de Janeiro',
  bairro: 'Tijuca',
  curso: 'Administração',
  turno: 'Manhã',
  modalidade: 'Presencial',
  alt: 'Logo da Faculdade Estácio',
  logo: 'https://cdn-icons-png.flaticon.com/512/2991/2991148.png',
  serie: '2ª',
  precoComDesconto: '1200,00'
},
{
  instituicao: 'Centro Universitário Senac',
  estado: 'SP',
  cidade: 'São Paulo',
  bairro: 'Vila Mariana',
  curso: 'Design Gráfico',
  turno: 'Noite',
  modalidade: 'EAD',
  alt: 'Logo do Centro Universitário Senac',
  logo: 'https://cdn-icons-png.flaticon.com/512/2721/2721435.png',
  serie: '3ª',
  precoComDesconto: '1300,00'
},
{
  instituicao: 'Universidade Paulista - UNIP',
  estado: 'SP',
  cidade: 'São Paulo',
  bairro: 'Liberdade',
  curso: 'Engenharia de Software',
  turno: 'Tarde',
  modalidade: 'Presencial',
  alt: 'Logo da UNIP',
  logo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png',
  serie: '4ª',
  precoComDesconto: '1600,00'
},
{
  instituicao: 'Universidade Anhembi Morumbi',
  estado: 'SP',
  cidade: 'São Paulo',
  bairro: 'Vila Olímpia',
  curso: 'Marketing',
  turno: 'Integral',
  modalidade: 'Presencial',
  alt: 'Logo da Universidade Anhembi Morumbi',
  logo: 'https://cdn-icons-png.flaticon.com/512/1998/1998606.png',
  serie: '1ª',
  precoComDesconto: '1800,00'
},
  
];
